// Generated by DN Figma Bridge - Updated to use CoreJourney
import React from 'react';
import { CoreJourney } from '@dankupfer/dn-components';

interface GeneratedEverydayProps {
  screenWidth: number;
}

const GeneratedEveryday: React.FC<GeneratedEverydayProps> = ({ screenWidth }) => {
  const customerData = {
    customerId: 'customer-1',
    profile: {
      id: 'profile-1',
      name: 'Sarah Johnson',
      email: 'sarah.johnson@email.com',
      age: 34,
      profession: 'Software Engineer'
    },
    accounts: [
      {
        id: 'current',
        name: 'Current Account',
        accountNumber: '12-34-56 / 12345678',
        sortCode: '12-34-56',
        balance: 2450.75,
        type: 'current' as const
      },
      {
        id: 'savings',
        name: 'Savings Account',
        accountNumber: '12-34-56 / 87654321',
        sortCode: '12-34-56',
        balance: 8750.20,
        type: 'savings' as const
      },
      {
        id: 'credit',
        name: 'Platinum Credit Card',
        accountNumber: '**** **** **** 1234',
        sortCode: '12-34-56',
        balance: -345.60,
        type: 'credit' as const
      }
    ],
    transactions: [
      {
        id: 'tx-1',
        accountId: 'current',
        amount: -45.20,
        description: 'Weekly shopping',
        date: 'Today',
        type: 'debit' as const,
        category: 'Groceries',
        merchant: 'Tesco'
      },
      {
        id: 'tx-2',
        accountId: 'current',
        amount: 2500.00,
        description: 'Monthly salary',
        date: '2 days ago',
        type: 'credit' as const,
        category: 'Income',
        merchant: 'Salary Payment'
      },
      {
        id: 'tx-3',
        accountId: 'credit',
        amount: -89.99,
        description: 'Online purchase',
        date: 'Yesterday',
        type: 'debit' as const,
        category: 'Shopping',
        merchant: 'Amazon'
      }
    ]
  };

  return (
    <CoreJourney
      customerData={customerData}
      customerId="customer-1"
      screenWidth={screenWidth}
      config={{
        showGreeting: true,
        showQuickActions: true,
        showTotalBalance: true,
        useCondensedAccounts: true
      }}
    />
  );
};

export default GeneratedEveryday;