// Generated by DN Figma Bridge
import React from 'react';
import { CoreJourney, ScreenBuilder, type ScreenConfig } from '@dankupfer/dn-components';
// import screenData from './screenData.json';

interface GeneratedSummaryProps {
    screenWidth: number;
}

const GeneratedSummary: React.FC<GeneratedSummaryProps> = ({ screenWidth }) => {
    //   const config = screenData as ScreenConfig;

    return (
        <CoreJourney
            config={{
                showGreeting: true,
                showTotalBalance: true,
                showQuickActions: true,
                showWallet: true,
                useCondensedAccounts: true,
            }}
            screenWidth={screenWidth}
        />
    );
};

export default GeneratedSummary;
