// Generated by DN Figma Bridge
import React from 'react';
import { ScreenBuilder, type ScreenConfig } from '@dankupfer/dn-components';
import screenData from './screenData.json';

interface GeneratedScreenProps {
  screenWidth: number;
}

const GeneratedScreen: React.FC<GeneratedScreenProps> = ({ screenWidth }) => {
  const config = screenData as ScreenConfig;
  
  return (
    <ScreenBuilder 
      config={config} 
      screenWidth={screenWidth} 
    />
  );
};

export default GeneratedScreen;
